# vue deployer
public_dir: dist

deploy:
  type: git
  repo:
    # github: https://github.com/Cenergy/cenergy.github.io.git
    # coding: https://e.coding.net/aigis/GISHAI.git
    GISHAI: root@GISHAI:/home/git/aigisss
  branch: master
